config/routes.rb
Tshtask::Application.routes.draw do
  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users, except: [:show, :index]
  resources :money, except: [:delete, :edit, :update, :create, :new] do
  	get :refresh_rates, on: :collection
  	get :report
  end
end

app/models/currency.rb
class Currency < ActiveRecord::Base
  belongs_to :exchange

  def self.create_from_node(node, exchange)
  	Currency.create(
  	  name: node.xpath("nazwa_waluty").inner_text,
  	  converter: node.xpath("przelicznik").inner_text,
  	  code: node.xpath("kod_waluty").inner_text,
  	  buy_price: node.xpath("kurs_kupna").inner_text.gsub(',','.').to_f,
  	  sell_price: node.xpath("kurs_sprzedazy").inner_text.gsub(',','.').to_f,
  	  exchange: exchange
  	)
  end

  def self.prices_hash
    prices = { buy: {}, sell: {} }
    all.each do |currency|
      prices[:buy][currency.exchange.created_at] = currency.buy_price
      prices[:sell][currency.exchange.created_at] = currency.sell_price
    end
    prices
  end
  
  def self.raport_hash
    {
      name: all.first.name,
      buy_data: all.statistics_hash('buy'),
      sell_data: all.statistics_hash('sell')
    }
  end

  def self.statistics_hash(action)
    prices = all.map(&"#{action}_price".to_sym).sort
    size = prices.size
    max = prices.max
    min = prices.min
    average = (prices.sum / size).round(4)
    median = (prices[(size - 1) / 2] + prices[size / 2]) / 2.0
    { max: max, min: min, average: average, median: median }
  end

end

app/models/exchange.rb
class Exchange < ActiveRecord::Base
  has_many :currencies

  require 'open-uri'

  attr_accessor :file
  
  paginates_per 10

  def self.get_new_rates
    exchange = Exchange.new
    exchange.get_nbp_xml
    exchange.save_current_rates
  end

  def get_nbp_xml
  	open('lastc.xml', 'wb') do |file|
      file << open('http://www.nbp.pl/kursy/xml/lastc.xml').read
      self.file = file
    end
  end

  def save_current_rates
  	xml = Nokogiri::XML(File.open(file)) { |config| config.strict.noblanks }
  	self.name = xml.xpath("//numer_tabeli")[0].inner_text
    if Exchange.last.nil? || Exchange.last.name != self.name
  		self.save
  	  xml.xpath("//pozycja").each { |node| Currency.create_from_node(node, self) }
  	end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/money_controller.rb
class MoneyController < ApplicationController
  before_action :authenticate_user!

  #show list of exchange rates with creation time
  #don't forget about pagination
  def index
    @exchanges = Exchange.all.reverse_order.page(params[:page])
  end

  #show table of currencies for selected exchange rate
  def show
    @exchange = Exchange.find(params[:id])
  end

  #for manual refreshing
  #get latest exchange rates and save to db
  #can be helpful: 
  #http://www.nbp.pl/home.aspx?f=/kursy/instrukcja_pobierania_kursow_walut.html
  def refresh_rates
    Exchange.get_new_rates
    redirect_to :back, alert: 'Downloaded exchange rates'
  end

  #generate a report for selected currency
  #report should show: basic statistics: mean, median, average
  #also You can generate a simple chart(use can use some js library)
  
  #this method should be available only for currencies which exist in the database 
  def report
    currency = Currency.where(code: params[:money_id])
    unless currency.empty?
      @currency_hash = currency.raport_hash
      @chart_prices = currency.prices_hash
      @exchange = params[:exchange]
    else
      redirect_to money_index_path, alert: 'Wrong currency'
    end
  end


end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :update_sanitized_params, if: :devise_controller?

  def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:name, :email, :password, :password_confirmation)}
    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:name, :email, :password, :password_confirmation, :current_password)}
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
%h3 Exchange application
- if signed_in?
  %p= link_to('Get exchange rates', refresh_rates_money_index_path)
  %p= link_to('Show list of exchange rates', money_index_path)

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "danger"}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Login', new_user_session_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
<% else %>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Tshtask'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Tshtask'}"}
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = javascript_include_tag "//www.google.com/jsapi", "chartkick"
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield

app/views/money/index.html.haml
%h3 Exchange Rates
%ul
  - @exchanges.each do |exchange|
    %li= link_to("#{exchange.name}, created at #{exchange.created_at}", money_path(exchange))
  = paginate @exchanges

app/views/money/report.html.haml
%h3= @currency_hash[:name]
%table{border:1}
  %thead
    %tr
      %th 
      %th Max
      %th Min
      %th Average
      %th Median
  %tbody 
    %tr
      %td Buy
      %td #{@currency_hash[:buy_data][:max]}
      %td #{@currency_hash[:buy_data][:min]}
      %td #{@currency_hash[:buy_data][:average]}
      %td #{@currency_hash[:buy_data][:median]}
    %tr
      %td Sell
      %td #{@currency_hash[:sell_data][:max]}
      %td #{@currency_hash[:sell_data][:min]}
      %td #{@currency_hash[:sell_data][:average]}
      %td #{@currency_hash[:sell_data][:median]}

= line_chart [ {name: "Buy prices", data: @chart_prices[:buy]}, 
               {name: "Sell prices", data: @chart_prices[:sell]} ]

= link_to('Back', money_path(@exchange))

app/views/money/show.html.haml
%h3 Exchange #{@exchange.name} - Currencies Table
%table
  %thead
    %tr
      %th Name
      %th Converter
      %th Code
      %th Buy price
      %th Sell price
  %tbody
    - @exchange.currencies.each do |currency|
      %tr
        %td= link_to("#{currency.name}", money_report_path(currency.code, exchange: @exchange.id))
        %td #{currency.converter}
        %td #{currency.code}
        %td #{currency.buy_price}
        %td #{currency.sell_price}

= link_to('Back', money_index_path)

app/views/users/edit.html.haml
= form_for(@user) do |f|
  = f.label :email
  = f.text_field :email
  %br/
  = f.submit "Update"